### ISSUE TITLE
Code of Conduct Update (help wanted) 

### ISSUE THREAD

**Issue by bluejayKR** [openinfradev/community#21]
Contributor Covenant 가 현재 v2.0 으로 바뀐듯 합니다. 
https://github.com/openinfradev/community/blob/main/code-of-conduct.md 

기존에 저희가 v1.2.0을 기준으로 작성이된 HANU Code of Conduct를 v2.0 기준으로 업데이트할 필요가 있지 않을까 합니다. 

추가로, v2.0에 대한 upstream translation 기여도 가능하지 않을까 하네요. (한국어 버전은 1.4만 존재를 해서)

**Comment by jabbukka** [comment]
v2.0 기준으로 번역 기여 도전해보겠습니다. 👊

**Comment by seokho-son** [comment]
@bluejayKR @jabbukka 안녕하세요. 쿠버네티스 문서 한글화팀에 손석호 입니다. 
HANU 구경 왔습니다.. ^^ 앞으로 좋은 오픈소스 커뮤니티로 거듭나길 기대합니다!

HANU 커뮤니티 행동 강령 v1.0 (https://github.com/openinfradev/community/blob/main/code-of-conduct.md) 
을 보니, 아마 CNCF의 커뮤니티 행동 강령 한글 문서를 활용하신 것 같네요 ^^

해당 CNCF 한글 문서의 번역 오류가 좀 있어서, 
최근에 업데이트 하였습니다. 참고하시면 좋을 것 같습니다. 
https://github.com/cncf/foundation/blob/master/code-of-conduct-languages/ko.md

**Comment by seokho-son** [comment]
Contributor Covenant 에서 번역된 것을 바로 사용하신 것이군요 ^^ 제가 착각을 ~

**Comment by bluejayKR** [comment]
> Contributor Covenant 에서 번역된 것을 바로 사용하신 것이군요 ^^ 제가 착각을 ~

앗, 관심 감사드립니다. 올려주신 내용은 좋은 참고가 될 것 같습니다. 
자주 구경하러 오셔서 좋은 의견 주세요~~ 감사합니다

**Comment by jabbukka** [comment]
[Pull Request #895](https://github.com/ContributorCovenant/contributor_covenant/pull/895) 올렸습니다.

**Comment by bluejayKR** [comment]
https://github.com/ContributorCovenant/contributor_covenant/pull/895 Merge 되었네요. Kudos to @jabbukka ! 
우리 것도 v2.0기반으로 업데이트 하면 좋을 것 같네요.
